name: Linux Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install System Deps
      run: sudo apt-get update && sudo apt-get install cmake build-essential -y pkg-config libasound2-dev libpulse-dev libjack-dev

    - name: Install Conan
      run: |
        pip install --break-system-packages conan
        conan profile detect --force

    - name: Run Build Script
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Run Exec Tests
      run: |
        ./build/client/babel_client 2> stderr.log
        
        if [ $? -ne 0 ];
          then echo "Binary crashed";
          exit 1;
        fi
        
        if [ -s stderr.log ]; then
          echo "Errors detected in stderr:"
          cat stderr.log
          exit 1
        fi

    - name: Upload Test
      uses: actions/upload-artifact@v4
      with:
        name: babel-client-linux
        path: build/client/babel_client