name: Windows Build

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Conan
      run: pip install conan && conan profile detect

    - name: Run Build Script
      run: .\build.bat
    
    - name: Run Smoke Test
      shell: pwsh
      run: |
        $stderrFile = "stderr.txt"
        Start-Process -FilePath ".\build\client\Release\babel_client.exe" -NoNewWindow -Wait -RedirectStandardError $stderrFile
        
        if (Test-Path $stderrFile) {
            $errContent = Get-Content $stderrFile
            if ($errContent) {
                Write-Error "Errors found in std::cerr: $errContent"
                exit 1
            }
        }